optimizer:
  _target_: torch.optim.SGD
  lr: 0.1
  momentum: 0.9
  dampening: 0
  weight_decay: 5e-4
  nesterov: true

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${max_epochs}
  eta_min: 0
