# reference: https://github.com/pytorch/examples/blob/main/imagenet/main.py
# number of epochs: 90

optimizer:
  _target_: torch.optim.SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 30
  gamma: 0.1

